export const ThirdPartyType = {
  PRIMARY_ENTITY: 'PRIMARY_ENTITY',
  COMPANY_AFFILIATE: 'COMPANY_AFFILIATE',
  THIRD_PARTY: 'THIRD_PARTY',
  VENDOR: 'VENDOR',
  PARTNER: 'PARTNER',
  CUSTOMER: 'CUSTOMER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
  BUSINESS_ASSOCIATE: 'BUSINESS_ASSOCIATE',
  OTHER: 'OTHER'
};
